version: '3.5'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - postgres

  postgres:
      container_name: pg_db
      image: postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: my_db
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

